# fly.toml app configuration file generated for array-of-sunshine on 2024-09-11T08:24:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = 'array-of-sunshine'
primary_region = 'lhr'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory_mb = 256
cpu_kind = 'shared'
cpus = 1

[[restart]]
policy = "on-failure"
retries = 2
processes = ["app"]
